title: Sparsh Tiwari # your name (or website title) here
logo: "/images/sparsh.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BE
  <br>
  Birla Institute Of Technology, Mesra
  <br>
  2014 - 2018
  <br><br>
  Seeking entry-level opportunities in ML/Data Science domain where i can help the company achieve future business goals with vision, mission and values. 
  <br><br>
  <a href="https://www.linkedin.com/in/sparshtiwari/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://drive.google.com/file/d/19F9J1Q6Hz6wulximm0ZrQ1aYlGwOYcYA/view?usp=sharing">View My Resume</a>
   
theme: jekyll-theme-minimal

