title: Sparsh Tiwari # your name (or website title) here
logo: "/images/sparsh.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BE
  <br>
  Birla Institute Of Technology, Mesra
  <br>
  2014 - 2018
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/sparshtiwari/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

