title: Sparsh Tiwari # your name (or website title) here
logo: "/images/sparsh.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BE
  <br>
  Birla Institute Of Technology, Mesra
  <br>
  2014 - 2018
  <br><br>
  A proactive and fast learning individual seeking an opportunity to work in machine learning/data science domain utilizing analytical and methodical skills, leveraging my 2 years of experience and recent Deep Learning studies to help the company achieve business goals with vision, mission and values. 
  <br><br>
  <a href="https://www.linkedin.com/in/sparshtiwari/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://drive.google.com/file/d/19F9J1Q6Hz6wulximm0ZrQ1aYlGwOYcYA/view?usp=sharing">View My Resume</a> 
theme: jekyll-theme-minimal

